### ISSUE TITLE
Tile management system (TMS) dynamic transition proposal

### ISSUE THREAD

**Issue by AaronLieb** [JustinStitt/acmBall2#1]
There are multiple proposals regarding how to transition the ball from one tile to another. 
Justin originally pitched this idea, and I've fleshed out some of the details in writing

### Find tiles that transition naturally together

If tiles have similar velocities, and positions at the transition point, pair them together.
We could write an exhaustive algorithm to do this that would accomplish the job well.

It could try all permutations possible and put the most inconvenient starting position as the starting tile and most inconvenient ending position as the ending tile. Optimize to maximize the number of tiles connected. It should consider that dynamic transition tiles can be used to get from any velocity and position to another velocity and position.

### Dynamic transition tiles

Create a variety of tiles that transition a specific position range and velocity range to an output position and output velocity.
Some suggestions for these tiles/components:
* Funnel (accepts almost any velocity, and can output at any other velocity. Its kinda boring)
* Tunnel (can be dynamically generated to accept any position and velocity and output at any pos or velocity.
* Slime (Can be used for velocity manipulation of the ball)
* Conveyor belt (Can be used for velocity manipulation)
* Water (Can float the ball, suppressing vertical velocity and keeping some slow horizontal velocity)
* Elevator (Cool animation, can take a slow moving ball and change its height without changing the horizontal velocity)
* Parachute (Float the ball to another location, maybe add wind to control position and velocity further)

We should get as creative as possible with these so we don't have any duplicates and so they are as fun as the tiles they are transitioning. 

### Feedback

Please give feedback if you have any other suggestions as to how this idea could be improved.

**Comment by AaronLieb** [comment]
@JustinStitt please review

**Comment by AaronLieb** [comment]
Just saw the TMS section in the design doc. "Generic" is definitely a better term than Dynamic Transition Tiles. Will use that in the future

**Comment by JustinStitt** [comment]
@AaronLieb Great ideas all around. Emphasis on keeping Generics fun and exciting.

We should flesh out an MVP with the boys soon.

**Comment by AaronLieb** [comment]
Diamond has suggested the following ideas:

### Chosen starting and ends points (Same as before)

The difference being that each team would choose their starting point with a UI or slider instead of hardcoding it, and the clients would use websockets to automatically communicate this with their respective neighbor and  display seamlessly, with no chance for conflicting values on two tiles. 

### Open map

Each tile is algorithmically placed in an open, non grid, map and can be placed anywhere. We would have bridges connecting the tiles and they could be as small or large as needed.

### My recommendation

Open map just seems like a lot of work and similar to the generics idea. Chosen start and end points worked decently well last time, and with the improvements mentioned, it would be even more seamless. No chance of mistakes, less time needed to communicate. I would recommend this method over the generics as well. 

Thoughts, @JustinStitt ?

**Comment by JustinStitt** [comment]
No setting end points at all. No communication between teams regarding ball positioning. TMS enables this.

Pretty set on this philosophy. Talk more IRL.

**Comment by JustinStitt** [comment]
We'll see how the Generics concept pans out because I think it's worth pursuing.

**Comment by diamondburned** [comment]
> No setting end points at all. No communication between teams regarding ball positioning. TMS enables this.

No communication is needed with the Open Map method. Tiles get automatically moved around by the algorithm onto a free map. Here's a rough sketch of the idea:

![image](https://user-images.githubusercontent.com/8463786/214245460-1485b9a4-4564-421b-8dc1-2599c30b5790.png)

The user won't even have to care about stating where the ball should exit. They only need to state where they want the ball to be and yeet the ball out wherever. The computer should take care of the rest.

The computer-generated map objects should have tolerance for inaccuracies: if the ball's properties differ during runtime than in calculation, then the objects should try and reset the ball's properties to be as expected while it's outside the map tiles. This ensures reproducibility.

> Open map just seems like a lot of work and similar to the generics idea.

I think there's a really trivial way to implement it. This pseudocode might work:

	define connectTiles(tiles):
		for each tileA in tiles:
			for each tileB in tiles:
				match (tileA.portal.direction, tileB.portal.direction):
					(left, right):
						# tileA portal is on the left, tileB portal is on
						# the right
						can connect
					(right, left):
						can connect
					(top, bottom):
						can connect
					(bottom, top):
						can connect
				# We cannot directly connect the tiles. Generate objects to
				# replace it.
				generateLinkingObjects(tileA, tileB)

	define generateLinkingObjects(tileA, tileB):
		linkObjects = [
			bouncingPlatform, # straight line, ball bounces off
			curvingSlide,     # ball slides along the platform
			launchingPad,     # ball lands on the pad, bounces up
		]

		for each object in linkingObjects:
			if object.isMostSuitable(tileA, tileB):
				object.link(tileA, tileB)
				return

Not to mention, it's much simpler to generate linking objects when they only need to be a small part of the map rather than having to computer-generate an entire tile on its own. This also allows user tiles to be of arbitrary shape and size, as long as the enter and exit regions exist.

> Pretty set on this philosophy. Talk more IRL.

When

**Comment by EthanThatOneKid** [comment]
> "Generic" is definitely a better term than Dynamic Transition Tiles. Will use that in the future

“Generated [structure]” may be a more accurate term. 

Edit: It's worth noting that ["generics"](https://en.m.wikipedia.org/wiki/Generic_programming) is a term commonly used in computer science to refer to a feature in programming languages that allows for creating classes, methods, and functions that can work with multiple types of data.

**Comment by AaronLieb** [comment]
@diamondburned Now that you explained it further and provided some visualization, I understand this concept much better. I'd be down to have a discussion about this. It appears promising and worthwhile.

**Comment by JustinStitt** [comment]
@diamondburned I am on board with your suggestion. Great stuff.

**Comment by AaronLieb** [comment]
We are going to move forward with the grid-less approach. Closing issue. Will open a new issue regarding implementation.
