### ISSUE TITLE
Code Submission Verification

### ISSUE THREAD

**Issue by AaronLieb** [JustinStitt/acmBall2#2]
Was talking to diamond about how code should be reviewed before being approved.

### Github Pull Request Bot

Create a submission endpoint, when received, creates a pull request to review it on github

### Simple Approval Endpoint

Add a submission endpoint and `/review` endpoint that lets us view all the pending code submissions, view the code, and approve the changes. No need for github pull requests, and would be simple and easy to use. 

### My recommendation

Simple approval endpoint seems simple to implement and effective. Would be happy with either option though.

cc: @JustinStitt

**Comment by EthanThatOneKid** [comment]
I agree with the provided recommendation. The _simple approval endpoint_ approach allows us to handle the submission process 100% our own way. For storing the code submissions and calculated TMS results, we can use Postgresql, JSONBin, or any decent database service.

**Comment by AaronLieb** [comment]
Implemented
